### ISSUE TITLE
Throws Error

### ISSUE THREAD

**Issue by manutursunov2311** [MarcinusX/bmi_calculator#13]
The following assertion was thrown building GenderCard(dirty, dependencies: [MediaQuery], state: _GenderCardState#eeae4):
'package:flutter/src/widgets/transitions.dart': Failed assertion: line 125 pos 15: 'listenable != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  Expanded file:///D:/FlutterProjects/simple_bmi_app/lib/input_page.dart:59:17
When the exception was thrown, this was the stack: 
#2      new AnimatedWidget (package:flutter/src/widgets/transitions.dart:125:15)
#3      new GenderArrow (package:simple_bmi_app/gender_card.dart:210:57)
#4      _GenderCardState._drawCircleIndicator (package:simple_bmi_app/gender_card.dart:90:9)
#5      _GenderCardState._drawMainStack (package:simple_bmi_app/gender_card.dart:75:11)
#6      _GenderCardState.build (package:simple_bmi_app/gender_card.dart:61:22)
...

**Comment by daniil-shumko** [comment]
What is the version of flutter are you using? Can you send what `flutter doctor` outputs?
